name: Selenium Login Tests

on: [push]

jobs:
  test-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar Chrome y Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r testsSelenium/requirements.txt

      - name: Ejecutar test de Login
        working-directory: ./testsSelenium
        run: |
          python -m pytest e2e/tests/testlogin.py \
            --html=e2e/reports/html_reports/login-report.html \
            --self-contained-html \
            -v  # Modo verbose para más detalles

      - name: Subir reporte del login
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: login-report
          path: testsSelenium/e2e/reports/html_reports/login-report.html