name: Selenium Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar Chrome y Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r testsSelenium/requirements.txt
          pip install webdriver-manager pytest-html

      - name: Ejecutar pruebas
        working-directory: ./testsSelenium  # Cambia el contexto de ejecución
        run: |
          python -m pytest e2e/tests/ \
            --html=e2e/reports/html_reports/test-report.html \
            --self-contained-html

      - name: Subir reporte
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selenium-report
          path: testsSelenium/e2e/reports/html_reports/test-report.html