name: Selenium Tests with Live Server

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias del frontend
        working-directory: ./src  # Carpeta de tu proyecto React/Vite
        run: npm install

      - name: Iniciar servidor de desarrollo en segundo plano
        working-directory: ./src
        run: npm run dev &  # El '&' permite ejecutar en segundo plano

      - name: Esperar que el servidor esté listo
        run: sleep 15  # Espera 15 segundos para que el servidor inicie

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar Chrome y Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Instalar dependencias de Python
        working-directory: ./testsSelenium
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas
        working-directory: ./testsSelenium
        run: |
          python -m pytest e2e/tests/testlogin.py \
            --html=e2e/reports/html_reports/login-report.html \
            --self-contained-html \
            -v

      - name: Subir reporte
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: login-report
          path: testsSelenium/e2e/reports/html_reports/login-report.html