name: Selenium Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager  # Instalación clave para manejar drivers

      - name: Ejecutar pruebas
        run: |
          python -m pytest tests/ \
            --html=test-report.html \
            --self-contained-html

      - name: Subir reporte de pruebas
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: selenium-report
          path: test-report.html